
class Config:	
	#RECAPTCHA_PUBLIC_KEY='6LcWAMYUAAAAAJAyEQcU8QAUCziOvTNJB-mJy5y7'
	#RECAPTCHA_PRIVATE_KEY='6LcWAMYUAAAAAK6QVhhbs5n6RbtHOB_DctRdPV-A'
	SECRET_KEY = '5791628bb0b13ce0c676dfde280ba245'
	SQLALCHEMY_DATABASE_URI = 'sqlite:///site.db'
	MAIL_SERVER='smtp.googlemail.com'
	MAIL_PORT=587
	MAIL_USE_TLS=True
	MAIL_USERNAME='kaifkhan3007@gmail.com'
	MAIL_PASSWORD=''
